import type { Metadata } from 'next'

import StyledComponentRegistry from '@/lib/registry'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentRegistry>
          <Providers>{children}</Providers>
        </StyledComponentRegistry>
      </body>
    </html>
  )
}
